# Generated by Django 4.1.4 on 2022-12-09 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Photo')),
                ('title', models.CharField(max_length=50, verbose_name='Photo Title')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Photo Descriprion')),
                ('people', models.CharField(blank=True, max_length=255, null=True, verbose_name='People on photo')),
                ('loacation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location of the photo')),
                ('tags', models.CharField(blank=True, max_length=100, null=True, verbose_name='Photo Search Tags')),
                ('cr_dt', models.DateTimeField(auto_now_add=True, verbose_name='Photo Created Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By User')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
