# Generated by Django 4.1.4 on 2022-12-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title', 'cr_dt']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='loacation',
            new_name='location',
        ),
    ]
